{% set name = "CellProfiler-Analyst" %}
{% set version = "2.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/CellProfiler-Analyst/archive/v{{ version }}.zip
  sha256: 299d1be28df0b9c35e856177ada7555746d5b94a0f7af34dc3c3dd3671252a6a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  skip: True  # [osx]
  noarch: generic

requirements:
  host:
    - pip
    - python <3
  run:
    - python <3
    - numpy
    - mock
    - python-bioformats
    - pandas
    - seaborn
    - scikit-learn
    - javabridge

test:
  imports:
    - cpa

about:
  home: https://github.com/CellProfiler/CellProfiler-Analyst
  license: 3-clause BSD license
  license_family: BSD
  summary: Allows interactive analysis of high-throughput of image data.
