{% set name = "CellProfiler-Analyst" %}
{% set version = "2.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/CellProfiler-Analyst/archive/{{ version }}.zip
  sha256: a08c3d088fcca18391f5cd4863409ea06d31012513a90d0f6519d4b27efe0597

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: generic

requirements:
  host:
    - pip
    - python <3
    - numpy
    - mock
    - python-bioformats
    - javabridge
  run:
    - python <3
    - pandas
    - seaborn
    - scikit-learn

test:
  imports:
    - cpa

about:
  home: https://github.com/CellProfiler/CellProfiler-Analyst
  license: 3-clause BSD license
  license_family: BSD
  summary: Allows interactive analysis of high-throughput of image data.
