{% set version = "0.1.4" %}
{% set name = "rust-ncbitaxonomy" %}
{% set sha256 = "7c3ca60bbddff1cfb24fcb1ba38b8fc25191127d8ccf967a316afd0431e6eda3" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

build:
  number: 0

source:
  url: "https://github.com/pvanheus/ncbitaxonomy/archive/{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.31.1

test:
  commands:
    - taxonomy_filter_refseq --help | grep NCBI

about:
  home: https://github.com/pvanheus/ncbitaxonomy
  doc_url: "https://docs.rs/crate/ncbitaxonomy/{{ version }}"
  license: MIT
  summary: |
    A Rust crate for working with a local copy of the NCBI Taxonomy database, which provides the taxonomy_filter_refseq commmand
