{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-flashclust
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.01_2"

source:
  fn: flashClust_1.01-2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/flashClust_1.01-2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/flashClust/flashClust_1.01-2.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('flashClust')" # [not win]
    - "\"%R%\" -e \"library('flashClust')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL (>= 2)
  summary: Fast implementation of hierarchical clustering
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: flashClust
# Version: 1.01-2
# Date: 2012-08-21
# Title: Implementation of optimal hierarchical clustering
# Author: code by Fionn Murtagh and R development team, modifications and packaging by Peter Langfelder
# Maintainer: Peter Langfelder <Peter.Langfelder@gmail.com>
# Depends: R (>= 2.3.0)
# ZipData: no
# License: GPL (>= 2)
# Description: Fast implementation of hierarchical clustering
# Packaged: 2012-08-21 17:18:30 UTC; plangfelder
# Repository: CRAN
# Date/Publication: 2012-08-21 18:23:43
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
