package:
  name: perl-class-accessor
  version: "0.34"

source:
  url: http://cpan.metacpan.org/authors/id/K/KA/KASEI/Class-Accessor-0.34.tar.gz
  md5: 0d9640d237a13276145f7e44b4855b89

build:
  number: 1

requirements:
  host:
    - perl

  run:
    - perl

test:
  imports:
    - Class::Accessor

about:
  home: http://metacpan.org/pod/Class::Accessor
  license: perl_5
  summary: 'Automated accessor generation'
