{% set ASAP_VERSION = "1.7.2" %}
package:
    name: asap_vis
    version: {{ ASAP_VERSION }}

source:
    fn: {{ ASAP_VERSION }}.zip
    url: https://github.com/GeertLitjens/ASAP/archive/{{ ASAP_VERSION }}.zip
    sha1: 45bc37cade2473e3be6cb71a2352f93dacfe6034

build:
    number: 0
    skip: True  # [py3k or osx]
    string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

requirements:
    build:
        - gcc   # [not osx]
        - llvm  # [osx]
        - cmake
        - python
        - boost {{CONDA_BOOST}}*
        - opencv >=2.4
        - qt >=5.1
        - libtiff >=4.0
        - jpeg
        - jasper
        - dcmtk
        - swig
        - openslide
        - pugixml
        - zlib

    run:
        - libgcc    # [not osx]
        - python
        - boost >=1.55
        - opencv >=2.4
        - qt >=5.1
        - libtiff >=4.0
        - jpeg
        - jasper
        - dcmtk
        - swig
        - openslide
        - pugixml
        - zlib

test:
    commands:
        - WSIThreshold | grep v{{ ASAP_VERSION }}

about:
   home: https://github.com/GeertLitjens/ASAP/
   license: GNU
   summary: ASAP is an open source platform for visualizing, annotating and automatically analyzing whole-slide histopathology images. It consists of several key-components (slide input/output, image processing, viewer) which can be used seperately. It is built on top of several well-developed open source packages like OpenSlide, Qt and OpenCV but also tries to extend them in several meaningful ways.
