{% set ASAP_VERSION = "1.6" %}
package:
    name: asap
    version: {{ ASAP_VERSION }}

source:
    fn: {{ ASAP_VERSION }}.zip
    url: https://github.com/GeertLitjens/ASAP/archive/{{ ASAP_VERSION }}.zip

build:
    number: 0
    skip: True  # [py3k or osx]

requirements:
    build:
        - gcc   # [linux]
        - cmake
        - python
        - boost >=1.55
        - opencv >=2.4
        - qt >=5.1
        - libtiff >=4.0
        - jpeg
        - jasper
        - dcmtk
        - swig
        - openslide
        - pugixml
        - zlib

    run:
        - python
        - boost >=1.55
        - opencv >=2.4
        - qt >=5.1
        - libtiff >=4.0
        - jpeg
        - jasper
        - dcmtk
        - swig
        - openslide
        - pugixml
        - zlib

test:
    commands:
        - WSIThreshold | grep v{{ ASAP_VERSION }}

about:
   home: https://github.com/GeertLitjens/ASAP/
   license: GNU
   summary: ASAP is an open source platform for visualizing, annotating and automatically analyzing whole-slide histopathology images. It consists of several key-components (slide input/output, image processing, viewer) which can be used seperately. It is built on top of several well-developed open source packages like OpenSlide, Qt and OpenCV but also tries to extend them in several meaningful ways.
