package:
  name: perl-sereal-encoder
  version: "3.015"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Encoder-3.015.tar.gz
  md5: 78428860e055561e371e3292093c1fc5

build:
  number: 1

requirements:
  host:
    - perl
    - perl-scalar-list-utils
    - perl-extutils-makemaker
    - perl-file-path
    - perl-pathtools
    - perl-test-longstring
    - perl-extutils-parsexs
    - perl-test-warn
    - perl-test-simple
    - perl-sereal-decoder

  run:
    - perl

test:
  imports:
    - Sereal::Encoder
    - Sereal::Encoder::Constants

about:
  home: http://metacpan.org/pod/Sereal::Encoder
  license: perl_5
  summary: 'Fast, compact, powerful binary serialization'
