package:
  name: trimadap
  version: "r10"

build:
  number: 0
  skip: True # [osx]

source:
  fn: trimadap_r10.tar.gz
  url: https://github.com/lh3/trimadap/archive/a577c413337df1fbc9c7ac11f925eb7dcc0e8209.tar.gz
  sha256: c5faee1dac1fb60629c69e677c50d2cb32fb3539

requirements:
  build:
  - gcc  # [not osx]
  - llvm  # [osx]
  - zlib

  run:
  - libgcc  # [not osx]
  - zlib

test:
  commands:
    - trimadap  2>&1 | grep trimadap > /dev/null

about:
  home: https://github.com/lh3/trimadap
  license: Unknown
  summary: Fast but inaccurate adapter trimmer for Illumina reads.

