{% set name = "OpenMS" %}
{% set version = "2.1.0" %}
package:
  name: {{ name|lower  }}
  version: {{ version  }}

source:
  fn: OpenMS-{{ version }}-src-contrib-docu.zip
  url: https://github.com/OpenMS/OpenMS/releases/download/Release{{ version }}/OpenMS-{{ version }}-src-contrib-docu.zip

build:
    number: 0
    skip: True  # [osx]

requirements:
  build:
    - gcc    # [linux]
    - llvm   # [osx]
    - cmake
    - autoconf
    - automake
    - python
    - zlib
    - libtool
    - xerces-c
    - gsl
    - boost  >=1.62.0
    - eigen
    - glpk  >=4.60
    - bzip2
    - qt
  run:
    - python
    - zlib
    - xerces-c
    - gsl
    - boost  >=1.62.0
    - eigen
    - glpk  >=4.60
    - bzip2
    - qt

test:
  commands:
    - FileMerger --help

about:
  home: https://github.com/OpenMS/OpenMS
  license: BSD
  summary: OpenMS is an open-source software C++ library for LC-MS data management and analyses
