{% set MKL_VERSION = "4.10.1" %}

package:
  name: mkl-dnn
  version: {{ MKL_VERSION }}

source:
  fn: v{{ MKL_VERSION }}.zip
  url: https://github.com/01org/mkl-dnn/archive/v{{ MKL_VERSION }}.zip
  md5: f7e7fb92ea3e11c78685c7977e0433d8

build:
    number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - cmake
  run:
    - python
    - libgcc    # [not osx]

test:
  commands:
    - test -f $PREFIX/lib/libmklml_gnu.so # [linux]

about:
  home: https://github.com/01org/mkl-dnn/
  license: Apache 2.0
  summary: Intel(R) Math Kernel Library for Deep Neural Networks (Intel(R) MKL-DNN) is an open source performance library for Deep Learning (DL) applications intended for acceleration of DL frameworks on Intel(R) architecture.
