{% set name = "lace" %}
{% set version = "0.76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/Oshlack/Lace/archive/0.76.tar.gz
  md5: b381cf4b672d21a9d7b47ecf6bb14833

requirements:
  build:

  run:
  - python
  - pandas
  - networkx
  - numpy
  - matplotlib
  - blat

test:
  commands:
    - Lace.py --help

about:
  home: https://github.com/Oshlack/Lace
  license: Unknown
  summary: 'Building SuperTranscripts: A linear representation of transcriptome data'
