{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-venn
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.2"

source:
  fn: venn_1.2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/venn_1.2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/venn/venn_1.2.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: QCA (>= 2.2), QCAGUI
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('venn')" # [not win]
    - "\"%R%\" -e \"library('venn')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL (>= 2)
  summary: Draws and displays Venn diagrams up to 7 sets, and any Boolean union of set intersections.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: venn
# Version: 1.2
# Date: 2016-05-04
# Title: Draw Venn Diagrams
# Authors@R: person("Adrian", "Dusa", role = c("aut", "cre", "cph"), email = "dusa.adrian@unibuc.ro")
# Depends: R (>= 3.0.0)
# Suggests: QCA (>= 2.2), QCAGUI
# Description: Draws and displays Venn diagrams up to 7 sets, and any Boolean union of set intersections.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2016-05-04 20:06:18 UTC; dusadrian
# Author: Adrian Dusa [aut, cre, cph]
# Maintainer: Adrian Dusa <dusa.adrian@unibuc.ro>
# Repository: CRAN
# Date/Publication: 2016-05-10 10:14:41

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
