package:
  name: cellh5
  version: "20.11.2017"

build:
  noarch: python
  script: "python -m pip install --no-deps --ignore-installed ."
  number: 0

source:
  url: https://github.com/CellH5/cellh5/archive/6997bbf21348bd8115357ad21a374155331da415.zip
  sha256: e1ac9af59de68483cb00ac782b74cb4b3214b45ec3d2fdacdd405144cfb86bbb

requirements:
  host:
    - python
    - pip
    - numpy
    - h5py
    - six
    - matplotlib
    - pyqt
    - qimage2ndarray
    - pandas
    - xorg-libx11
    - lxml
  run:
    - python
    - six
    - h5py
    - matplotlib
    - pyqt
    - qimage2ndarray
    - pandas
    - numpy

test:
  imports:
    - cellh5

about:
  home: https://github.com/CellH5/cellh5
  license: Github default
  summary: 'CellH5 is an HDF5 data format for cell-based assays in high-throughput microscopy'
