{% set name = "python-bioformats" %}
{% set version = "1.5.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/python-bioformats/archive/v{{ version }}.zip
  sha256: 299d1be28df0b9c35e856177ada7555746d5b94a0f7af34dc3c3dd3671252a6a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  skip: True  # [osx]

requirements:
  host:
    - pip
    - python <3
  run:
    - python <3
    - setuptools_scm
    - boto3
    - javabridge>=1.0

test:
  imports:
    - cpa

about:
  home: https://github.com/CellProfiler/python-bioformats
  license: 3-clause BSD license
  license_family: BSD
  summary: Python-bioformats is a Python wrapper for Bio-Formats, a standalone Java library for reading and writing life sciences image file formats.
