{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wgcna
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.51"

source:
  fn: WGCNA_1.51.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/WGCNA_1.51.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/WGCNA/WGCNA_1.51.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: org.Hs.eg.db, org.Mm.eg.db, infotheo, entropy, minet
requirements:
  build:
    - r-base
    - bioconductor-annotationdbi
    - bioconductor-go.db
    - r-hmisc
    - r-doparallel
    - r-dynamictreecut >=1.62
    - r-fastcluster
    - r-foreach
    - bioconductor-impute
    - r-matrixstats >=0.8.1
    - bioconductor-preprocesscore
    - r-survival
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-base
    - bioconductor-annotationdbi
    - bioconductor-go.db
    - r-hmisc
    - r-doparallel
    - r-dynamictreecut >=1.62
    - r-fastcluster
    - r-foreach
    - bioconductor-impute
    - r-matrixstats >=0.8.1
    - bioconductor-preprocesscore
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('WGCNA')" # [not win]
    - "\"%R%\" -e \"library('WGCNA')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.genetics.ucla.edu/labs/horvath/CoexpressionNetwork/Rpackages/WGCNA/
  license: GPL (>= 2)
  summary: Functions necessary to perform Weighted Correlation Network Analysis on high-dimensional
    data. Includes functions for rudimentary data cleaning, construction of correlation
    networks, module identification, summarization, and relating of variables and modules
    to sample traits. Also includes a number of utility functions for data manipulation
    and visualization.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: WGCNA
# Version: 1.51
# Date: 2016-03-08
# Title: Weighted Correlation Network Analysis
# Author: Peter Langfelder <Peter.Langfelder@gmail.com> and Steve Horvath <SHorvath@mednet.ucla.edu> with contributions by Chaochao Cai, Jun Dong, Jeremy Miller, Lin Song, Andy Yip, and Bin Zhang
# Maintainer: Peter Langfelder <Peter.Langfelder@gmail.com>
# Depends: R (>= 3.0), dynamicTreeCut (>= 1.62), fastcluster
# Imports: stats, grDevices, utils, matrixStats (>= 0.8.1), Hmisc, impute, splines, foreach, doParallel, preprocessCore, survival, parallel, GO.db, AnnotationDbi
# Suggests: org.Hs.eg.db, org.Mm.eg.db, infotheo, entropy, minet
# ZipData: no
# License: GPL (>= 2)
# Description: Functions necessary to perform Weighted Correlation Network Analysis on high-dimensional data. Includes functions for rudimentary data cleaning, construction of correlation networks, module identification, summarization, and relating of variables and modules to sample traits. Also includes a number of utility functions for data manipulation and visualization.
# URL: http://www.genetics.ucla.edu/labs/horvath/CoexpressionNetwork/Rpackages/WGCNA/
# NeedsCompilation: yes
# Packaged: 2016-03-14 22:18:51 UTC; plangfelder
# Repository: CRAN
# Date/Publication: 2016-03-15 00:24:08

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
