package:
  name: perl-proc-fork
  version: "0.804"

source:
  url: https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Proc-Fork-0.804.tar.gz
  md5: 0fd512eb21f365a11d9ff7de3b77a624

build:
  number: 1

requirements:
  host:
    - perl >=5.22.0
    - perl-exporter-tidy

  run:
    - perl >=5.22.0
    - perl-exporter-tidy

test:
  imports:
    - Proc::Fork

about:
  home: http://github.com/ap/Proc-Fork
  license: perl_5
  summary: 'simple, intuitive interface to the fork() system call'

