
package:
  name: cgat-scripts-nosetests
  version: 0.1

source:
  git_url: https://github.com/CGATOxford/cgat.git
#  git_rev: d22b4f20ba05109de3aa17487137de427b00457e

build:
  number: 0
  entry_points:
    - cgat = CGAT.cgat:main

requirements:
  build:
    # system deps
    - nomkl
    - gcc  # [linux]
    - llvm # [osx]
    - zlib
    # bioinformatics tools
    - bedtools
    - samtools
    - ucsc-wigtobigwig
    - ucsc-bedtobigbed
    - ucsc-bedgraphtobigwig
    # python deps
    - python
    - biopython
    - cython
    - alignlib-lite
    - bx-python # [py27]
    - future
    - ggplot
    - jinja2
    - matplotlib
    - networkx
    - nose
    - numpy
    - openpyxl
    - pandas
    - pep8
    - pybedtools
    - pysam
    - python-weblogo
    - rdflib
    - rpy2
    - scipy
    - setuptools
    - six
    - scikit-learn
    - pyyaml
    # R deps
    - r

  run:
    # system deps
    - nomkl
    - gcc  # [linux]
    - llvm # [osx]
    - zlib
    # bioinformatics tools
    - bedtools
    - samtools
    - ucsc-wigtobigwig
    - ucsc-bedtobigbed
    - ucsc-bedgraphtobigwig
    # python deps
    - python
    - biopython
    - cython
    - alignlib-lite
    - bx-python # [py27]
    - future
    - ggplot
    - jinja2
    - matplotlib
    - networkx
    - nose
    - numpy
    - openpyxl
    - pandas
    - pep8
    - pybedtools
    - pysam
    - python-weblogo
    - rdflib
    - rpy2
    - scipy
    - setuptools
    - six
    - scikit-learn
    - pyyaml
    # R deps
    - r

test:
  requires:
    # system deps
    - nomkl
    - gcc  # [linux]
    - llvm # [osx]
    - zlib
    # bioinformatics tools
    - bedtools
    - samtools
    - ucsc-wigtobigwig
    - ucsc-bedtobigbed
    - ucsc-bedgraphtobigwig
    # python deps
    - python
    - biopython
    - cython
    - alignlib-lite
    - bx-python # [py27]
    - future
    - ggplot
    - jinja2
    - matplotlib
    - networkx
    - nose
    - numpy
    - openpyxl
    - pandas
    - pep8
    - pybedtools
    - pysam
    - python-weblogo
    - rdflib
    - rpy2
    - scipy
    - setuptools
    - six
    - scikit-learn
    - pyyaml
    # R deps
    - r

  commands:
    - cd $SRC_DIR
    - export C_INCLUDE_PATH=$PREFIX/include
    # workaround while bx-python is py3 ready
    # https://github.com/bxlab/bx-python/issues/9
    - pip install bx-python
    - python setup.py develop
#    - echo -e "restrict:\n    manifest:\n" > tests/_test_scripts.yaml
    - nosetests -v tests/test_import.py
    - nosetests -v tests/test_scripts.py
    - cgat --help

about:
  home: https://www.cgat.org/downloads/public/cgat/documentation/
  license: BSD
  summary: "Computational Genomics Analysis Toolkit"

