{% set VERSION = "0.3.0" %}

package:
    name: bazel
    version: {{ VERSION }}

source:
    fn: bazel-{{ VERSION }}.tar.gz
    url: https://github.com/bazelbuild/bazel/archive/{{ VERSION }}.tar.gz
    sha256: d2309c29781dc4ede79eb652776517ca3c1dff29b58849dc80bdb86031cce3ad

build:
    number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - libarchive
    - pkg-config
    - git
    - protobuf
    - zip
    - unzip
    - java-jdk >=8
  run:
    - zip
    - unzip
    - java-jdk >=8
    - libgcc    # [not osx]
    - libarchive

test:
    commands:
        - bazel --help

about:
    home: http://www.bazel.io/
    license: Apache License, Version 2.0
    summary: 'A build tool that builds code quickly and reliably.'
