{% set VERSION = "0.3.0" %}

package:
    name: bazel
    version: {{ VERSION }}

source:
    fn: bazel-{{ VERSION }}.tar.gz
    url: https://github.com/bazelbuild/bazel/archive/{{ VERSION }}.tar.gz
    sha256: 2bb8e10018426c6bee415937612ba777b7a3779bc02a7dbb27b96a7440cc2a02

build:
    number: 0

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - libarchive
    - pkg-config
    - git
    - protobuf
    - zip
    - unzip
    - java-jdk >=8
  run:
    - python
    - libgcc    # [not osx]
    - zlib
    - libtiff
    - libpng
    - jpeg

about:
    home: http://www.bazel.io/
    license: Apache License, Version 2.0
    summary: 'A build tool that builds code quickly and reliably.'
