{% set KNIME_VERSION = "3.3.1" %}

package:
    name: knime
    version: {{ KNIME_VERSION }}

source:
    fn: knime_{{ KNIME_VERSION }}.linux.gtk.x86_64.tar.gz
    url: https://download.knime.org/analytics-platform/linux/knime_{{ KNIME_VERSION }}.linux.gtk.x86_64.tar.gz # [linux]
    md5: 64929872d687b04a624d76d121fd07af

build:
  number: 0
  skip: True # [osx]

requirements:
    run:
      - openjdk

test:
    commands:
      - knime -consoleLog -application org.knime.product.KNIME_BATCH_APPLICATION -nosplash

about:
    home: http://www.knime.org/
    license: GPL
    summary: "KNIME, the Konstanz Information Miner, is an open source data analytics, reporting and integration platform. "


