package:
  name: perl-sereal-decoder
  version: "3.015"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Decoder-3.015.tar.gz
  md5: de91784e359e25aee07f87a8b9b2f90b

build:
  number: 1

requirements:
  host:
    - perl
    - perl-file-path
    - perl-test-warn
    - perl-test-simple
    - perl-extutils-makemaker
    - perl-test-longstring
    - perl-scalar-list-utils
    - perl-pathtools
    - perl-extutils-parsexs

  run:
    - perl

test:
  imports:
    - Sereal::Decoder
    - Sereal::Decoder::Constants
    - Sereal::Performance

about:
  home: http://metacpan.org/pod/Sereal::Decoder
  license: perl_5
  summary: 'Fast, compact, powerful binary deserialization'

