package:
  name: visceral-evaluatesegmentation
  version: "2015.07.02"

source:
  fn: EvaluateSegmentation-2015.07.02-Ubuntu.zip
  url: https://github.com/Visceral-Project/EvaluateSegmentation/raw/master/builds/Ubuntu/EvaluateSegmentation-2015.07.02-Ubuntu.zip

build:
  number: 1

#test:
#  commands:
#    - EvaluateSegmentation --help > /dev/null

about:
  home: https://github.com/Visceral-Project/EvaluateSegmentation
  license: "Apache License, Version 2.0"
  summary: "EvaluateSegmentation is a tool that compares two volumes (a test segmentation and a ground truth segmentation) using 22 different metrics that were selected as a result of a comprehensive research into the metrics used in the medical volume segmentations."
