package:
  name: centrosome
  version: "1.1.6"

build:
  noarch: python
  number: 0

source:
  url: https://github.com/CellProfiler/centrosome/archive/v{{version}}.zip
  sha256: 628a05dbf1b3f3916a82229b4f13a6454f1c22cebfcb213cd42cec6212ce84ca

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - pytest
  run:
    - python
    - deprecation
    - matplotlib
    - numpy
    - pillow
    - scikit-image
    - scipy

test:
  imports:
    - centrosome

about:
  home: https://github.com/CellProfiler/centrosome
  license: BSD 3
  summary: 'Dependency for CellProfiler'
