{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dynamictreecut
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.63_1"

source:
  fn: dynamicTreeCut_1.63-1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/dynamicTreeCut_1.63-1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/dynamicTreeCut/dynamicTreeCut_1.63-1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dynamicTreeCut')" # [not win]
    - "\"%R%\" -e \"library('dynamicTreeCut')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.genetics.ucla.edu/labs/horvath/CoexpressionNetwork/BranchCutting/
  license: GPL (>= 2)
  summary: Contains methods for detection of clusters in hierarchical clustering dendrograms.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: dynamicTreeCut
# Version: 1.63-1
# Date: 2016-03-10
# Title: Methods for Detection of Clusters in Hierarchical Clustering Dendrograms
# Author: Peter Langfelder <Peter.Langfelder@gmail.com> and Bin Zhang <binzhang.ucla@gmail.com>,  with contributions from Steve Horvath <SHorvath@mednet.ucla.edu>
# Maintainer: Peter Langfelder <Peter.Langfelder@gmail.com>
# Depends: R (>= 2.3.0), stats
# ZipData: no
# License: GPL (>= 2)
# Description: Contains methods for detection of clusters in hierarchical clustering dendrograms.
# URL: http://www.genetics.ucla.edu/labs/horvath/CoexpressionNetwork/BranchCutting/
# NeedsCompilation: no
# Packaged: 2016-03-10 18:25:27 UTC; plangfelder
# Repository: CRAN
# Date/Publication: 2016-03-11 00:39:02

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
