{% set version = "2.16" %}
{% set sha256 = "ad81a8da4b60f358430d4ee63f340fd378f66c95dbed63d9ab57ab6eae6a1c3c" %}

package:
  name: mlst
  version: '{{ version }}'

source:
  url: https://github.com/tseemann/mlst/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  run:
    - blast >=2.7.1
    - perl-bioperl >=1.7.2
    - perl-moo
    - perl-list-moreutils
    - perl-json
    - zlib

test:
  commands:
    - mlst --version
    - mlst --check
    - mlst --list 2>&1 | grep leptospira > /dev/null

about:
  home: https://github.com/tseemann/mlst
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Scan contig files against PubMLST typing schemes

extra:
  identifiers:
    - biotools:mlst
