{% set CUDAMAT_VERSION = "09.09.2016" %}

package:
  name: cudamat
  version: {{ CUDAMAT_VERSION }}

source:
  fn: cudamat-6f4dbc773bfd0fa2b1d38939837b9019ac21d26e.zip
  url: https://github.com/cudamat/cudamat/archive/6f4dbc773bfd0fa2b1d38939837b9019ac21d26e.zip
  md5: 3641a81623d0bd37689abe69fd9ed924

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - cudatoolkit
  run:
    - python
    - numpy

test:
  imports:
    - cudamat

about:
  home: https://github.com/cudamat/cudamat
  license: All Rights Reserved
  summary: The aim of the cudamat project is to make it easy to perform basic matrix calculations on CUDA-enabled GPUs from Python. 
