package:
  name: fermikit
  version: "0.14.dev1"

build:
  number: 0

source:
  fn: fermikit-0.14.dev1.tar.bz2
  url: https://github.com/lh3/fermikit/archive/96f7820c91b01113abf24f4d30cf86a89d8a1ccc.tar.gz
  sha256: c4f5474fb6f6d23427fbf10564de0606621015ef585f88df0ca0e97353db0fec

requirements:
  build:
  - gcc  # [not osx]
  - llvm  # [osx]
  - zlib

  run:
  - libgcc  # [not osx]
  - perl
  - zlib
  - bfc ==r181
  - bwa ==0.7.15
  - fermi2 ==r193
  - htsbox ==r327
  - ropebwt2 ==r187
  - seqtk ==r82
  - trimadap ==r10

test:
  commands:
    - fermi2.pl unitig -s5k -t1 -l100 -p phi_test test.fastq > phi_test.mak && make -f phi_test.mak

about:
  home: https://github.com/lh3/fermikit
  license: Unknown
  summary: FermiKit is a de novo assembly based variant calling pipeline for deep Illumina resequencing data.

