package:
  name: fermikit
  version: "0.13"

build:
  number: 0

source:
  fn: fermikit-0.13.tar.bz2
  url: https://github.com/lh3/fermikit/releases/download/v0.13/fermikit-0.13.tar.bz2
  sha256: 067c7b8b5ddcac417f5c95d9138abe3077df9d147d6dc50ae7d4a563ac5ad82f

requirements:
  build:
  - gcc
  - zlib

  run:
  - libgcc
  - perl

test:
  commands:
    - fermi2.pl unitig -s5k -t1 -l100 -p phi_test test.fastq

about:
  home: https://github.com/lh3/fermikit
  license: Unknown
  summary: FermiKit is a de novo assembly based variant calling pipeline for deep Illumina resequencing data.

